server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false

